# Generated by Django 5.1.3 on 2025-01-24 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.contracttype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='function',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.function'),
        ),
        migrations.AddField(
            model_name='employee',
            name='language',
            field=models.ManyToManyField(to='vacancies.language'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skill',
            field=models.ManyToManyField(to='vacancies.skill'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeegallery',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_gallery', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employergallery',
            name='employers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers_gallery', to='accounts.employer'),
        ),
        migrations.AddField(
            model_name='review',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_reviews', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='review',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_reviews', to='accounts.employer'),
        ),
    ]
