# Generated by Django 5.1.3 on 2025-02-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_admin_user_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
