# Generated by Django 5.1.3 on 2024-12-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="phone_session_counts",
            field=models.IntegerField(default=0),
        ),
    ]
