# Generated by Django 5.1.3 on 2025-03-04 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gallery", models.ImageField(upload_to="galleries/")),
                (
                    "employers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_gallery",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
