# Generated by Django 5.1.3 on 2025-03-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usergallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employergallery',
            name='employers',
        ),
        migrations.RenameField(
            model_name='usergallery',
            old_name='employers',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='EmployeeGallery',
        ),
        migrations.DeleteModel(
            name='EmployerGallery',
        ),
    ]
