# Generated by Django 5.1.1 on 2024-12-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employeegallery_employergallery'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.contracttype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='function',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.function'),
        ),
        migrations.AddField(
            model_name='employee',
            name='language',
            field=models.ManyToManyField(to='common.language'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skill',
            field=models.ManyToManyField(to='common.skill'),
        ),
        migrations.AddField(
            model_name='employee',
            name='week_day',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
