# Generated by Django 5.1.3 on 2024-12-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employee_contract_type_employee_function_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='week_day',
        ),
    ]
