# Generated by Django 5.1.3 on 2025-01-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_employee_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('employer', 'Employer')], max_length=10, null=True),
        ),
    ]
