# Generated by Django 5.1.3 on 2025-03-17 12:25

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_employee_date_of_birth_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_banner',
            field=models.ImageField(blank=True, help_text="User's profile banner image (max 5MB, jpg, jpeg, png, gif)", null=True, upload_to='profile_banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture (max 5MB, jpg, jpeg, png, gif)", null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.models.validate_image_size]),
        ),
    ]
