# Generated by Django 5.1.3 on 2025-03-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_employee_date_of_birth_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Designates whether this user is blocked from accessing the platform.'),
        ),
    ]
