# Generated by Django 5.1.3 on 2025-03-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_employers', to='accounts.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_employees', to='accounts.employer')),
            ],
            options={
                'unique_together': {('employer', 'employee')},
            },
        ),
    ]
