# Generated by Django 5.1.3 on 2025-03-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_likedemployee'),
        ('vacancies', '0008_sector_function_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='The business sector this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='vacancies.sector'),
        ),
    ]
