# Generated by Django 5.1.3 on 2025-03-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='likedemployee',
            options={'ordering': ['-created_at']},
        ),
    ]
