# Generated by Django 5.1.3 on 2025-03-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_employee_options_alter_likedemployee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id']},
        ),
    ]
