# Generated by Django 5.1.3 on 2025-03-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_update_profile_relationships'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
    ]
