# Generated by Django 5.1.3 on 2025-03-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_employee_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_number', models.CharField(max_length=20, unique=True)),
                ('is_valid', models.BooleanField()),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_validations', to='accounts.employer')),
            ],
            options={
                'verbose_name': 'VAT Validation Result',
                'verbose_name_plural': 'VAT Validation Results',
                'ordering': ['-validation_date'],
            },
        ),
    ]
