# Generated by Django 5.1.3 on 2025-03-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_vatvalidationresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
