# Generated by Django 4.2.20 on 2025-03-31 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20250325_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vat_number', models.CharField(max_length=30, unique=True)),
                ('street_name', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='vatvalidationresult',
            name='employer',
        ),
        migrations.AddField(
            model_name='likedemployee',
            name='liked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_employees_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatvalidationresult',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_validations_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likedemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_companies', to='accounts.employee'),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
                'unique_together': {('company', 'user')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='companies', through='accounts.CompanyUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likedemployee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customuser',
            name='selected_company',
            field=models.ForeignKey(blank=True, help_text='The currently selected company for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_users', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='likedemployee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_employees', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='vatvalidationresult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_validations', to='accounts.company'),
        ),
        migrations.AlterUniqueTogether(
            name='likedemployee',
            unique_together={('company', 'employee')},
        ),
        migrations.RemoveField(
            model_name='likedemployee',
            name='employer',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
