# Generated by Django 4.2.20 on 2025-03-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_company_remove_vatvalidationresult_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='coordinates',
        ),
    ]
