# Generated by Django 4.2.20 on 2025-03-31 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0016_remove_vacancy_employer_vacancy_company_and_more'),
        ('accounts', '0025_remove_company_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sector',
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='The business sector this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector', to='vacancies.sector'),
        ),
    ]
