# Generated by Django 4.2.20 on 2025-03-31 12:00

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_customuser_sector_company_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_banner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_banner',
            field=models.ImageField(blank=True, help_text="User's profile banner image (max 5MB, jpg, jpeg, png, gif)", null=True, upload_to='profile_banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture (max 5MB, jpg, jpeg, png, gif)", null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.models.validate_image_size]),
        ),
    ]
