# Generated by Django 4.2.20 on 2025-03-31 12:07

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_company_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_banner',
            field=models.ImageField(blank=True, help_text="Company's profile banner image (max 5MB, jpg, jpeg, png, gif)", null=True, upload_to='company_profile_banners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='company',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Company's profile picture (max 5MB, jpg, jpeg, png, gif)", null=True, upload_to='company_profile_pictures/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.models.validate_image_size]),
        ),
    ]
