# Generated by Django 5.1.3 on 2025-04-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_allow_null_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.CharField(blank=True, help_text="Number of employees in the company (e.g., '1-10', '11-50', '51-200', etc.)", max_length=50, null=True),
        ),
    ]
