# Generated by Django 5.1.3 on 2025-04-02 06:26

import common.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_company_employee_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(help_text='Company gallery image (max 5MB, jpg, jpeg, png, gif)', upload_to='company_galleries/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), common.utils.validate_image_size])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_gallery', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Company Gallery',
                'verbose_name_plural': 'Company Galleries',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='UserGallery',
        ),
    ]
