# Generated by Django 5.1.3 on 2025-04-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_employee_availability_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='longitude',
        ),
    ]
