# Generated by Django 5.1.3 on 2025-04-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_employee_latitude_remove_employee_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, help_text="Link to company's Facebook profile", null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_url',
            field=models.URLField(blank=True, help_text="Link to company's Instagram profile", null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text="Link to company's TikTok profile", null=True),
        ),
    ]
