# Generated by Django 5.1.3 on 2025-05-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_add_employee_language"),
        ("vacancies", "0026_merge_20250415_0840"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="language",
            field=models.ManyToManyField(
                blank=True,
                related_name="employees",
                through="accounts.EmployeeLanguage",
                to="vacancies.language",
            ),
        ),
    ]
