# Generated by Django 5.1.3 on 2025-05-05 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_alter_employee_language"),
        ("vacancies", "0026_merge_20250415_0840"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="employment_type",
        ),
        migrations.CreateModel(
            name="EmployeeQuestionPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancies.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Question Prompt",
                "verbose_name_plural": "Employee Question Prompts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="prompts",
            field=models.ManyToManyField(
                blank=True, to="accounts.employeequestionprompt"
            ),
        ),
    ]
