# Generated by Django 5.1.3 on 2025-05-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_remove_employee_employment_type_and_more"),
        ("vacancies", "0026_merge_20250415_0840"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="interests",
            field=models.ManyToManyField(blank=True, to="vacancies.profileinterest"),
        ),
    ]
