# Generated by Django 5.1.3 on 2025-05-05 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_employee_interests"),
        ("vacancies", "0027_experienceschool_experiencecompany"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                help_text="The business sector this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="vacancies.sector",
            ),
        ),
    ]
