# Generated by Django 5.1.3 on 2025-05-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_fix_employee_language"),
        ("vacancies", "0027_experienceschool_experiencecompany"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employeelanguage",
            name="unique_employee_language",
        ),
        migrations.AlterUniqueTogether(
            name="employeelanguage",
            unique_together={("employee", "language")},
        ),
    ]
