# Generated by Django 4.2.22 on 2025-06-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0028_add_liked_vacancy"),
        ("accounts", "0044_remove_employeelanguage_unique_employee_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="week_day",
            field=models.ManyToManyField(blank=True, to="vacancies.weekday"),
        ),
    ]
