# Generated by Django 5.1.3 on 2025-06-23 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_employee_week_day'),
        ('vacancies', '0028_add_liked_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.contracttype'),
        ),
    ]
