services:
  api:
    network_mode: "host"
    build: 
      context: jobr_api_backend
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./jobr_api_backend:/app
    ports:
      - "8000:8000"