# Generated by Django 5.1.3 on 2025-05-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0001_initial"),
    ]

    operations = [
        # No operations needed, we'll handle the Employee language field in a separate migration
    ]
