# Generated by Django 5.1.3 on 2025-05-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workexperience",
            name="employment_type",
        ),
    ]
