# Generated by Django 5.1.3 on 2025-06-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_workexperience_employment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"verbose_name": "Education", "verbose_name_plural": "Education"},
        ),
        migrations.RemoveField(
            model_name="education",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="education",
            name="start_date",
        ),
    ]
