# Generated by Django 5.1.3 on 2025-03-04 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_rename_timestamp_message_created_at_and_more"),
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="vacancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatrooms_vacancy",
                to="vacancies.vacancy",
            ),
        ),
    ]
