# Generated by Django 5.1.3 on 2025-03-06 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_vacancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(related_name='chatroom_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
