# Generated by Django 5.1.3 on 2025-03-17 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='extra',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='extra',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='extra',
            name='extra',
            field=models.CharField(help_text='Additional data', max_length=255),
        ),
    ]
