# Generated by Django 5.1.3 on 2025-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contracttype',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='function',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
