# Generated by Django 5.1.3 on 2025-01-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_location'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='location',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.ManyToManyField(to='common.location'),
        ),
    ]
