# Generated by Django 5.1.3 on 2025-03-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="contract_type",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="contract_type",
            field=models.ManyToManyField(blank=True, to="vacancies.contracttype"),
        ),
    ]
