# Generated by Django 5.1.3 on 2025-03-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_joblistingprompt_profileinterest_salarybenefit_and_more'),
        ('vacancies', '0002_remove_vacancy_contract_type_vacancy_contract_type'),
    ]

    operations = [
    ]
