# Generated by Django 5.1.3 on 2025-01-24 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_location'),
        ('vacancies', '0002_remove_vacancy_location_vacancy_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='language',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='question',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='expected_mastery',
            field=models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='location',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='week_day',
        ),
        migrations.CreateModel(
            name='VacancyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.question')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='descriptions',
            field=models.ManyToManyField(to='vacancies.vacancydescription'),
        ),
        migrations.CreateModel(
            name='VacancyLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.language')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='languages',
            field=models.ManyToManyField(related_name='vacancy_languages', to='vacancies.vacancylanguage'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='questions',
            field=models.ManyToManyField(to='vacancies.vacancyquestion'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.location'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='week_day',
            field=models.ManyToManyField(null=True, to='vacancies.weekday'),
        ),
    ]
