# Generated by Django 5.1.3 on 2025-03-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_merge_20250310_1347'),
        ('vacancies', '0003_merge_20250316_1322'),
    ]

    operations = [
    ]
