# Generated by Django 5.1.3 on 2025-03-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_merge_20250316_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='week_day',
            field=models.ManyToManyField(blank=True, to='vacancies.weekday'),
        ),
    ]
