# Generated by Django 5.1.3 on 2024-12-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0004_vacancy_signed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="signed_by",
        ),
    ]
