# Generated by Django 5.1.3 on 2024-12-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_remove_vacancy_signed_by'),
    ]

    operations = [
    ]
