# Generated by Django 5.1.1 on 2024-12-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('vacancies', '0005_remove_vacancy_signed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.contracttype'),
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.function'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='language',
            field=models.ManyToManyField(to='common.language'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='question',
            field=models.ManyToManyField(to='common.question'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skill',
            field=models.ManyToManyField(to='common.skill'),
        ),
        migrations.DeleteModel(
            name='ContractType',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
