# Generated by Django 5.1.3 on 2025-03-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_vacancy_latitude_vacancy_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_benefits',
            field=models.ManyToManyField(blank=True, to='vacancies.salarybenefit'),
        ),
    ]
