# Generated by Django 5.1.3 on 2025-03-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_vacancy_salary_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='functions', to='vacancies.skill'),
        ),
    ]
