# Generated by Django 5.1.3 on 2025-03-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_sector_function_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='vacancies.function'),
        ),
    ]
