# Generated by Django 5.1.3 on 2025-03-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_remove_function_skills_skill_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='function',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='weight',
        ),
        migrations.CreateModel(
            name='FunctionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1, help_text='Weight of this skill for this specific function')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.function')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.skill')),
            ],
            options={
                'ordering': ['-weight'],
                'unique_together': {('function', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='function',
            name='skills',
            field=models.ManyToManyField(related_name='functions', through='vacancies.FunctionSkill', to='vacancies.skill'),
        ),
    ]
