# Generated by Django 5.1.3 on 2025-03-25 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_admin_user_alter_employee_user_and_more'),
        ('vacancies', '0013_fix_rename_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyvacancy',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
