# Generated by Django 4.2.20 on 2025-03-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_alter_applyvacancy_employee_alter_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
