# Generated by Django 4.2.20 on 2025-03-31 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0024_company_remove_vatvalidationresult_employer_and_more'),
        ('vacancies', '0015_sector_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='employer',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vacancies', to=settings.AUTH_USER_MODEL),
        ),
    ]
