# Generated by Django 4.2.20 on 2025-03-31 12:32

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0016_remove_vacancy_employer_vacancy_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='icon',
            field=models.ImageField(blank=True, help_text="Sector's icon (max 5MB, jpg, jpeg, png, gif, svg)", null=True, upload_to='sector_icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg']), common.utils.validate_image_size]),
        ),
    ]
