# Generated by Django 5.1.3 on 2025-04-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_add_sector_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='expected_mastery',
            field=models.CharField(choices=[('None', 'none'), ('Beginner', 'beginner'), ('Intermediate', 'intermediate'), ('Advanced', 'advanced'), ('Expert', 'expert')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancylanguage',
            name='mastery',
            field=models.CharField(choices=[('None', 'none'), ('Beginner', 'beginner'), ('Intermediate', 'intermediate'), ('Advanced', 'advanced'), ('Expert', 'expert')], max_length=255),
        ),
    ]
