# Generated by Django 5.1.3 on 2025-04-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0020_add_application_status_and_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionskill',
            options={'ordering': ['weight']},
        ),
    ]
