# Generated by Django 5.1.3 on 2025-04-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0024_add_internal_function_title'),
        ('vacancies', '0024_add_responsibilities'),
    ]

    operations = [
    ]
