# Generated by Django 5.1.3 on 2025-04-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0025_merge_20250414_2119'),
        ('vacancies', '0025_update_vacancy_description_prompt'),
    ]

    operations = [
    ]
