# Generated by Django 5.1.3 on 2025-05-05 11:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0026_merge_20250415_0840"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        help_text="Company's logo (max 5MB, jpg, jpeg, png, gif)",
                        upload_to="company_logos",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        help_text="Company's logo (max 5MB, jpg, jpeg, png, gif)",
                        upload_to="company_logos",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        help_text="The business sector this company belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="experience_companies",
                        to="vacancies.sector",
                    ),
                ),
            ],
        ),
    ]
