# Generated by Django 4.2.22 on 2025-06-08 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_remove_employeelanguage_unique_employee_language_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vacancies", "0027_experienceschool_experiencecompany"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikedVacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_vacancies",
                        to="accounts.employee",
                    ),
                ),
                (
                    "liked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_vacancies_as_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_by_employees",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("employee", "vacancy")},
            },
        ),
    ]
